export const statusCodes = {
  SUCCESS: "00",
  CIF_SUCCESS: "01",
  SERVICE_NOT_AVAILABLE: "55",
  DUPLICATE_REQUEST: "77",
  BAD_REQUEST: "99",
  UNAUTHORIZED: "41",
  PROFILE_LINKED_ALREADY: "62",
  BAD_REQUEST_HTTP_CODE: 400,
  UNAUTHORIZED_HTTP_CODE: 401,
  SERVER_ERROR_HTTP_CODE: 500,
  FETCH_ERROR: "FETCH_ERROR",
};

export const validationMode = {
  PIN: "PIN",
  OTP: "OTP",
  TOKEN: "TOKEN",
};
